// Mocks generated by Mockito 5.4.6 from annotations
// in khadamaty_app/test/booking_test/createbooking_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:khadamaty_app/core/error/failures.dart' as _i5;
import 'package:khadamaty_app/features/auth/domain/entities/user_entity.dart'
    as _i8;
import 'package:khadamaty_app/features/auth/domain/repositories/auth_repository.dart'
    as _i7;
import 'package:khadamaty_app/features/bookings/domain/entities/booking_entity.dart'
    as _i6;
import 'package:khadamaty_app/features/bookings/domain/repositories/booking_repository.dart'
    as _i3;
import 'package:khadamaty_app/features/bookings/domain/usecases/create_booking_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingRepository extends _i1.Mock implements _i3.BookingRepository {
  MockBookingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> createBooking(
          _i6.BookingEntity? booking) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBooking,
          [booking],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #createBooking,
            [booking],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookingEntity>>> getUserBookings(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserBookings,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookingEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BookingEntity>>(
          this,
          Invocation.method(
            #getUserBookings,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookingEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookingEntity>>>
      getProviderBookings(String? providerId) => (super.noSuchMethod(
            Invocation.method(
              #getProviderBookings,
              [providerId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.BookingEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BookingEntity>>(
              this,
              Invocation.method(
                #getProviderBookings,
                [providerId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookingEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateBookingStatus(
    String? bookingId,
    _i6.BookingStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookingStatus,
          [
            bookingId,
            status,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateBookingStatus,
            [
              bookingId,
              status,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i8.UserEntity?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i8.UserEntity?>.empty(),
      ) as _i4.Stream<_i8.UserEntity?>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>> register({
    required String? name,
    required String? phone,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #name: name,
            #phone: phone,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i5.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #name: name,
              #phone: phone,
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i5.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> sendEmailVerification() =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #sendEmailVerification,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isEmailVerified() =>
      (super.noSuchMethod(
        Invocation.method(
          #isEmailVerified,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isEmailVerified,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity?>> reloadUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #reloadUser,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity?>>.value(
            _FakeEither_0<_i5.Failure, _i8.UserEntity?>(
          this,
          Invocation.method(
            #reloadUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> sendPasswordResetEmail(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #sendPasswordResetEmail,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [CreateBookingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateBookingUseCase extends _i1.Mock
    implements _i9.CreateBookingUseCase {
  MockCreateBookingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> call(_i6.BookingEntity? booking) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [booking],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #call,
            [booking],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
