// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNwOhR4vx1GF3lesKGkXFXdPCG-UzWMxc',
    appId: '1:961338466870:web:fdc728d007c862f4086e97',
    messagingSenderId: '961338466870',
    projectId: 'khadamatyapp-32861',
    authDomain: 'khadamatyapp-32861.firebaseapp.com',
    storageBucket: 'khadamatyapp-32861.firebasestorage.app',
    measurementId: 'G-R73J727VFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChy7XqgpIo2xvtddgDiSfclNSgpMT-2Tk',
    appId: '1:961338466870:android:2a1b1765b1e2470a086e97',
    messagingSenderId: '961338466870',
    projectId: 'khadamatyapp-32861',
    storageBucket: 'khadamatyapp-32861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWo0Yj-7LBaMkd2SUswMjCiEZRrmgX_DM',
    appId: '1:961338466870:ios:25e2aeb95eeccabf086e97',
    messagingSenderId: '961338466870',
    projectId: 'khadamatyapp-32861',
    storageBucket: 'khadamatyapp-32861.firebasestorage.app',
    iosBundleId: 'com.abdelrahman.khadamaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWo0Yj-7LBaMkd2SUswMjCiEZRrmgX_DM',
    appId: '1:961338466870:ios:7bf56ef505ae0aac086e97',
    messagingSenderId: '961338466870',
    projectId: 'khadamatyapp-32861',
    storageBucket: 'khadamatyapp-32861.firebasestorage.app',
    iosBundleId: 'com.example.khadamatyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNwOhR4vx1GF3lesKGkXFXdPCG-UzWMxc',
    appId: '1:961338466870:web:e1106ac1fcec8290086e97',
    messagingSenderId: '961338466870',
    projectId: 'khadamatyapp-32861',
    authDomain: 'khadamatyapp-32861.firebaseapp.com',
    storageBucket: 'khadamatyapp-32861.firebasestorage.app',
    measurementId: 'G-5YNHX9E8WE',
  );
}
